#!/bin/bash
# The set command is used to determine action if error 
# is encountered.  (-e) will stop and exit (+e) will 
# continue with the script.
set -e

##################################################################################################################
# Written to be used on 64 bits computers
# Author 	: 	Brett Crisp
##################################################################################################################

sudo pacman -Syyu --noconfirm

yay -Syyu --noconfirm

mkdir ~/DATA

chmod +x -R ~/DATA*

cd ~/DATA

[ -d ~/DATA/arco-xfce-brett ] || git clone https://github.com/Sugarcrisp-ui/arco-xfce-brett

cd ~/DATA/arco-xfce-brett

sh 100-display-manager-and-xfce-desktop*
sh 110-install-core-software*
sh 200-software-AUR-repo*

cd ~/DATA/arco-xfce-brett/AUR

#sh appimagelauncher*
sh authy*
sh gnome-disk-utility*
sh cryptomator*
sh github-desktop*
sh gnome-gtkhash*
sh ice-dev*
sh mcmojave-circle-icon-theme-git*
sh realvnc-vnc-server*
sh realvnc-vnc-viewer*

cd ~/DATA/arco-xfce-brett/Personal

sh 666-uninstall-applications*
sh 667-uninstall-arcolinux-meta-steam*
sh 700-installing-fonts*
sh 900-install-personal-settings-folders*
sh 915-install-personal-settings-screenshot-to-jpg*
sh 930-autostart-applications*
sh 950-install-all-fonts-needed-for-conkys-of-arcolinux*
sh 955-install-settings-autoconnect-to-bluetooth-headset*
sh 997-makepkg-name-email*
sh fix-pamac-aur*

cd ~/DATA

[ -d ~/DATA/personal-settings ] || git clone https://github.com/Sugarcrisp-ui/personal-settings

cd ~/DATA/personal-settings

cp .bashrc-personal /home/brett/.bashrc-personal

cp .gtkrc-2.0.mine /home/brett/.gtkrc-2.0.mine

#cp -a config/autostart/ /home/brett/.config/

#cp -a config/Thunar/ /home/brett/.config/

#cp -a config/variety/ /home/brett/.config/

cp -a bin-personal/ /home/brett/.bin-personal

cp -a scr /home/brett/

#cd ~/DATA

#[ -d ~/DATA/xfce-config ] || git clone https://github.com/Sugarcrisp-ui/xfce-config

#cd ~/DATA/xfce-config

#cp bashrc-personal /home/brett/.bashrc-personal

#cp -a autostart/ /home/brett/.config/

#cp -a Thunar/ /home/brett/.config/

#cp -a variety/Fetched/ /home/brett/.config/variety/Fetched/

#cp -a xfce-perchannel-xml/ /home/brett/.config/xfce4/xfconf/xfce-perchannel-xml/

tput setaf 1
echo "################################################################"
echo "JUST FOR THE COMPUTER OF BRETT CRISP"
echo "INTEL BASED GRAPHICAL CARD"
echo "################################################################"
tput sgr0
