#!/bin/bash
# The set command is used to determine action if error 
# is encountered.  (-e) will stop and exit (+e) will 
# continue with the script.
set -e

##################################################################################################################
# Written to be used on 64 bits computers
# Author 	: 	Brett Crisp
##################################################################################################################

sudo pacman -Syu --noconfirm

yay -Syu --noconfirm

mkdir ~/DATA

chmod +x -R ~/DATA*

cd ~/DATA

[ -d ~/DATA/arco-xfce-brett ] || git clone https://github.com/Sugarcrisp-ui/arco-xfce-brett

cd ~/DATA/arco-xfce-brett

sh 100-display-manager-and-xfce-desktop*
sh 110-install-core-software*
sh 200-software-AUR-repo*

cd ~/DATA/arco-xfce-brett/AUR

# Following apps are disabled for testing of script to save time

sh appimagelauncher*
sh authy*
sh gnome-disk-utility*
sh cryptomator-v1*
#sh gnome-gtkhash-v1*
sh ice-dev-v1*
sh mcmojave-circle-icon-theme-git*
sh realvnc-vnc-server*
sh realvnc-vnc-viewer-v1*

cd ~/DATA/arco-xfce-brett/Personal

sh 666-uninstall-applications*
sh 667-uninstall-arcolinux-meta-steam*
sh 700-installing-fonts*
sh 900-install-personal-settings-folders*
sh 915-install-personal-settings-screenshot-to-jpg*
sh 930-autostart-applications*
sh 950-install-all-fonts-needed-for-conkys-of-arcolinux*
sh 955-install-settings-autoconnect-to-bluetooth-headset-v*
sh 997-makepkg-name-email-v1*
sh fix-pamac-aur*

cd ~/DATA

[ -d ~/DATA/xfce-config ] || git clone https://github.com/Sugarcrisp-ui/xfce-config

cd ~/DATA/xfce-config

cp bashrc-personal ~/.bashrc-personal

cp -r autostart/. ~/.config/

cp -r Thunar/. ~/.config/

cp -r variety/Fetched/. ~/.config/variety/Fetched/

cp -r xfce-perchannel-xml/. ~/.config/xfce4/xfconf/xfce-perchannel-xml/

tput setaf 1
echo "################################################################"
echo "JUST FOR THE COMPUTER OF BRETT CRISP"
echo "INTEL BASED GRAPHICAL CARD"
echo "################################################################"
tput sgr0
