#!/bin/bash
#
##################################################################################################################
# Written to be used on 64 bits computers
# Author 	: 	Erik Dubois
# Website 	: 	http://www.erikdubois.be
##################################################################################################################
##################################################################################################################
#
#   DO NOT JUST RUN THIS. EXAMINE AND JUDGE. RUN AT YOUR OWN RISK.
#
##################################################################################################################


sudo pacman -Syyu --noconfirm

yay -Syu --noconfirm

cp -r DATA ~
#cp -r VirtualBox\ VMs/ ~

chmod +x -R ~/DATA/*

cd ~/DATA

[ -d ~/DATA/arco-xfce-brett ] || git clone https://github.com/Sugarcrisp-ui/arco-xfce-brett

cd ~/DATA/arco-xfce-brett

sh 100-display-manager-and-xfce-desktop*
sh 110-install-core-software*
sh 200-software-AUR-repo*

cd ~/DATA/arco-xfce-brett/AUR

sh authy*
sh gnome-disk-utility*
sh cryptomator-v1*
sh gnome-gtkhash-v1*
sh ice-dev-v1*
sh mcmojave-circle-icon-theme-git*
sh realvnc-vnc-viewer-v1*

cd ~/DATA/arco-xfce-brett/Personal

sh 666-uninstall-applications*
sh 667-uninstall-arcolinux-meta-steam*
sh 700-installing-fonts*
sh 900-install-personal-settings-folders*
sh 915-install-personal-settings-screenshot-to-jpg*
sh 930-autostart-applications*
sh 950-install-all-fonts-needed-for-conkys-of-arcolinux*
sh 955-install-settings-autoconnect-to-bluetooth-headset-v*
sh 997-makepkg-name-email-v1*
sh fix-pamac-aur*
tput setaf 1
echo "################################################################"
echo "JUST FOR THE COMPUTER OF BRETT CRISP"
echo "INTEL BASED GRAPHICAL CARD"
echo "################################################################"
tput sgr0
